Distmysql 162 release notes pdps 8.0.28
percona/pdmysql-docs pull request #42
Opened 2022-04-12 09:25 UTC by nastena1606

2022-04-12 10:00 UTC, patrickbirch approved these changes
LGTM

2022-04-13 09:51 UTC, LenzGr approved these changes
LGTM, thank you!

2022-04-26 08:08 UTC, EvgeniyPatlan requested changes

2022-04-26 08:08 UTC, EvgeniyPatlan commented on source/release-notes-ps-v8.0.28.rst
> +     - 8.0.28-17.0
as I remember it is 8.0.28-20

2022-04-27 07:53 UTC, EvgeniyPatlan approved these changes

2022-05-12 17:52 UTC, merged